### Create user
POST http://localhost:3000/user
Content-Type: application/json

{
    "username": "demo4",
    "password": "demo4"
}

### Update user
PUT http://localhost:3000/user
Content-Type: application/json

{
    "id": 23,
    "username": "demo2",
    "password": "demo2edit"
}

### Delete user
DELETE http://localhost:3000/user
Content-Type: application/json

{
    "id": 4
}

### Search user
GET http://localhost:3000/user/search?q=d
Content-Type: application/json
